name: offline_music_player
description: "Simple Offline Music Player built with Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # Audio playback
  just_audio: ^0.10.5
  audio_service: ^0.18.12
  audio_session: ^0.2.2

  # State management
  provider: ^6.1.1
  rxdart: ^0.28.0

  # Local storage & persistence
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1

  # Permissions & file access
  permission_handler: ^12.0.1
  file_picker: ^10.3.7

  # UI helpers
  palette_generator: ^0.3.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
